### ISSUE TITLE
UNKNOWN ERROR 

### ISSUE THREAD

**Issue by Aprinnetwork** [kittoku/Minimum-VPN-Client-for-SoftEther-VPN#12]
Hello, 
It's me again 😉 with another issue regarding connection, but this time with Softether Client. Once I try to connect to the server I get the error. I've attached the log file. T U 🙏🏻

**Comment by Aprinnetwork** [comment]
Log file 
[log_mvc_20221122094642.txt](https://github.com/kittoku/Minimum-VPN-Client-for-SoftEther-VPN/files/10064460/log_mvc_20221122094642.txt)

**Comment by kittoku** [comment]
This is a known issue (#1).

**Comment by Aprinnetwork** [comment]
Here's the point my server address is not binary.

**Comment by Aprinnetwork** [comment]
> 



> This is a known issue (#1).

Here's the point my server address is not binary.

**Comment by kittoku** [comment]
Binary means precompiled program, not address.

**Comment by Aprinnetwork** [comment]
> Binary means precompiled program, not address.

Pardon me for the lack of info, I have no choice but to find a way to connect to my server. Every way that you could imagine is censored in our current situation. I have no idea about that.

**Comment by kittoku** [comment]
All I can say is that this app is not a solution, which is just experimental.

**Comment by Aprinnetwork** [comment]
> All I can say is that this app is not a solution, which is just experimental.

Sure, Thank's for your time. ⚘
