### ISSUE TITLE
Softeather config to android

### ISSUE THREAD

**Issue by shock-wave007** [kittoku/Minimum-VPN-Client-for-SoftEther-VPN#5]
![image](https://user-images.githubusercontent.com/29371789/147389614-2a9a8ada-4e3f-4b62-b360-d8eae7253d66.png)

i fill these fields and does not change any of the setting.(red)
and BLUE field is auto fill

Q1. i wanna know what kind of connection this might be (SoftEther protocol / L2TP/IPSec PSK / or something else)
Q2. how can i connect it on my android 

iam new to vpn stuff and i am trying to connect the config (from work) i have for pc on my android

**Comment by kittoku** [comment]
I'm afraid this is a experimental project. 

I recommend that you ask or search questions in [SoftEther forum](https://www.vpnusers.com/) after reading [documents which SoftEther provides](https://www.softether.org/4-docs)!
